### ISSUE TITLE
OSX

### ISSUE THREAD

**Issue by lesterpang** [vova616/screenshot#12]
`github.com/vova616/screenshot/screenshot_darwin.go:49: cannot use rawData (type C.CFDataRef) as type C.CFTypeRef in argument to func literal`

**Comment by kesarion** [comment]
@lesterpang Please add compilable code to reproduce the issue and any system/compiler/tool versions you find relevant.

**Comment by dpineda-ob** [comment]
+1

**Comment by dpineda-ob** [comment]
+1
go version go1.8 darwin/amd64

same error doing 'go get github.com/vova616/screenshot'   and 'xgo github.com/vova616/screenshot'

**Comment by kesarion** [comment]
xgo must have a stricter linter/compiler config to catch this one, standard go build/install works just fine. It shouldn't have been an issue, functionality-wise, but now xgo should be happy and compile.
