### ISSUE TITLE
Panic in BitBlt

### ISSUE THREAD

**Issue by lkarlslund** [vova616/screenshot#18]
I have experienced a panic in BitBlt. This is hardly necessary to trigger panics in your package, when you could just return an error.

panic: BitBlt failed

goroutine 12 [running]:
myproject/vendor/github.com/vova616/screenshot.BitBlt(0xffffffff920134ee, 0x0, 0x0, 0x31c, 0x4c, 0xffffffff90011059, 0xbe4, 0x824, 0xcc0020)
myproject/vendor/github.com/vova616/screenshot/screenshot_windows.go:140 +0xed
myproject/vendor/github.com/vova616/screenshot.CaptureRect(0xbe4, 0x824, 0xf00, 0x870, 0x0, 0x0, 0x0)
	myproject/sectionGuard/vendor/github.com/vova616/screenshot/screenshot_windows.go:74 +0x310
main.GetTraybarBackground(0xc04224cf50, 0xc04234b301, 0x0, 0x0)
	myproject/main.go:30 +0xfe

**Comment by jamesduncombe** [comment]
I added some error handling around this on a fork. I need to PR it though... https://github.com/jamesduncombe/screenshot/commits/fix/bitblt

**Comment by jamesduncombe** [comment]
PR added... hopefully it can get merged in.

**Comment by vova616** [comment]
looks good to me
