### ISSUE TITLE
Windows 10 scaling issue

### ISSUE THREAD

**Issue by waylandc** [vova616/screenshot#19]
Screenshot (using example program) works fine with I have scaling at 100%. But if I change scaling (say 125% or 150%), screenshot doesn't capture entire screen

**Comment by Glowned** [comment]
Same here

**Comment by wangnanlena** [comment]
change
	HORZRES          = 118
	VERTRES          = 117
in  screenshot_windows.go will fix this.

**Comment by Kif11** [comment]
@wangnanlena this worked. What are those numbers?

**Comment by vova616** [comment]
Looks like this

''' Vertical height of entire desktop in pixels
DESKTOPVERTRES = 117
''' Horizontal width of entire desktop in pixels
DESKTOPHORZRES = 118

thanks @wangnanlena pushed a fix
